// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef labfin_h
#define labfin_h
#include <FL/Fl.H>
// This is a soccer shoting game. Players need to shoot the ball without
// letting the ball be captured by the goalie so the player could score.
// The goalie will move horizontally from left side of the goal to the
// right. Platers click the screen to shoot the ball. If they miss the
// goal, the player would have to start over again. If they score, 
// there is a rank system to cout their rank level. The goalie will move 
// faster and faster each time the player scores

// There are two buttons on the homepage of this game:the "instructions"
// button and the "start" button. by clicking the "instructions" button,
// it willlead the player to another window which shows instructions of
// the game and how to play it. then they will click the "return" 
// button to return to the home screen. Then they click the "start" 
// button to start the game. The player needs to click on the screen
// to shoot the ball. If they score, their rank level will get higher.
// If the goalie catches the ball. the rank level will drop all the 
// way down to the beginning again

// {\begin{alltt}
// - The game logo is on top of the home screen.
// - the two buttons are on the left side of the home screen called
// "press start" and "instructions".
// -when you click on "instructions", it will take you to another 
// window which would show the instructions, and there would be a 
// return button to go back to the home screen.
// -the press start button will take you to another window which the 
// game exists.
// -the game window, would have a soccer ball and a goal, and near the 
// goal would be a zombie goalie running left and right.
// \end{alltt}
// }
void load_images();
void goalie2_animate(void*);
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *IScreen;
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *InstructionTD;
extern Fl_Double_Window *MainScreen;
#include <FL/Fl_Box.H>
extern Fl_Box *Goalie2;
extern Fl_Box *Gamelogo;
#include <FL/Fl_Button.H>
extern Fl_Button *Instructions;
extern Fl_Button *Startgame;
#endif
// {\
// For test, we only need to compile the progam using fltk and open it
// to see if any error has occured. if no error occured, we would do
// ./labfin to see if it has compiled the way we intended it to. 
// and that the things we want there is displaying. The orginal image
// for some reason is not displaying. so i took a screenshot of it.
// \includegraphics{design.png}\\
// \includegraphics[scale=0.5]{design2.png}\\
// }
